ECHO OFF
IF EXIST COMM1-PM.txt GOTO SWITCH_TO_NIGHT
IF EXIST COMM1-AM.txt GOTO SWITCH_TO_DAY

ECHO AMBIGUITY--IS COMM1.txt intended as a day or night command? Create an empty COMM1-AM.txt or COMM1-PM.txt series to clarify.
GOTO END

:SWITCH_TO_NIGHT

IF EXIST COMM1.txt REN COMM1.txt COMM1-AM.txt
IF EXIST COMM2.txt REN COMM2.txt COMM2-AM.txt
IF EXIST COMM3.txt REN COMM3.txt COMM3-AM.txt

IF EXIST COMM1-PM.txt REN COMM1-PM.txt COMM1.txt
IF EXIST COMM2-PM.txt REN COMM2-PM.txt COMM2.txt
IF EXIST COMM3-PM.txt REN COMM3-PM.txt COMM3.txt

GOTO END

:SWITCH_TO_DAY

IF EXIST COMM1.txt REN COMM1.txt COMM1-PM.txt
IF EXIST COMM2.txt REN COMM2.txt COMM2-PM.txt
IF EXIST COMM3.txt REN COMM3.txt COMM3-PM.txt

IF EXIST COMM1-AM.txt REN COMM1-AM.txt COMM1.txt
IF EXIST COMM2-AM.txt REN COMM2-AM.txt COMM2.txt
IF EXIST COMM3-AM.txt REN COMM3-AM.txt COMM3.txt

GOTO END

:END
EXIT